# Generated by Django 4.2.11 on 2024-04-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
