# Generated by Django 4.2.11 on 2024-04-12 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_name'),
        ('orders', '0002_alter_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orders.OrderedItem', to='items.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
