# Generated by Django 4.2.11 on 2024-04-12 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_ordereditem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_preparation_time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
