# Generated by Django 4.2.11 on 2024-04-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('starter', 'starter'), ('main_dish', 'main_dish'), ('dessert', 'dessert')], max_length=20, unique=True),
        ),
    ]
